spring.application.name=spring-data-jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=macbook
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=analiz_ai_db